# Generated by Django 4.2.30 on 2026-07-31 10:21

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('STAFF', 'Staff'), ('HOD', 'Head of Department'), ('CAMPUS_ADMIN', 'Campus Admin'), ('SYSTEM_ADMIN', 'System Admin')], default='STUDENT', max_length=15),
        ),
    ]
