# Generated by Django 4.2.30 on 2026-08-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_unused_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_number',
            field=models.CharField(blank=True, default='', help_text='Exactly 10 digits (e.g. 98XXXXXXXX).', max_length=10),
        ),
    ]
