# Generated by Django 4.2.30 on 2026-07-10 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Description of the grievance (10 to 5000 characters).')),
                ('current_status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('SPAM', 'Spam'), ('UNDER_REVIEW', 'Under Review'), ('RESPONDED', 'Responded'), ('REOPENED', 'Reopened'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='SUBMITTED', max_length=20)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('secret_code', models.CharField(blank=True, help_text='Unique secret code issued to anonymous submitters for tracking.', max_length=20, null=True)),
                ('is_reopened', models.BooleanField(default=False, help_text='Flag distinguishing repeated review cycles from the first pass.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='The classification category of the grievance.', on_delete=django.db.models.deletion.PROTECT, related_name='grievances', to='grievances.category')),
                ('department', models.ForeignKey(help_text='The department responsible for handling this grievance.', on_delete=django.db.models.deletion.PROTECT, related_name='grievances', to='accounts.department')),
                ('user', models.ForeignKey(help_text='The submitting user (retained internally for audits even if submitted anonymously).', on_delete=django.db.models.deletion.CASCADE, related_name='grievances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('SPAM', 'Spam'), ('UNDER_REVIEW', 'Under Review'), ('RESPONDED', 'Responded'), ('REOPENED', 'Reopened'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], max_length=20)),
                ('new_status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('SPAM', 'Spam'), ('UNDER_REVIEW', 'Under Review'), ('RESPONDED', 'Responded'), ('REOPENED', 'Reopened'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], max_length=20)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_by', models.ForeignKey(blank=True, help_text='User who triggered this transition (null if triggered by system auto-escalation).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_actions', to=settings.AUTH_USER_MODEL)),
                ('grievance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='grievances.grievance')),
            ],
            options={
                'verbose_name': 'Status History',
                'verbose_name_plural': 'Status Histories',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='The body content of the response.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grievance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='grievances.grievance')),
                ('responder', models.ForeignKey(help_text='The HOD who responded to the grievance.', on_delete=django.db.models.deletion.PROTECT, related_name='responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='grievance_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('grievance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='grievances.grievance')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spam_prediction', models.BooleanField(default=False, help_text='True if flagged as spam by AI.')),
                ('confidence_score', models.FloatField(help_text='Spam confidence score between 0.0 and 1.0.')),
                ('classification_reason', models.TextField(blank=True, default='')),
                ('sentiment', models.CharField(blank=True, help_text='Future sentiment analysis output.', max_length=50, null=True)),
                ('analysis_timestamp', models.DateTimeField(auto_now_add=True)),
                ('grievance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='grievances.grievance')),
            ],
            options={
                'verbose_name': 'AI Analysis',
                'verbose_name_plural': 'AI Analyses',
            },
        ),
    ]
