# Generated by Django 4.2.30 on 2026-07-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statushistory',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('SUBMITTED', 'Submitted'), ('SPAM', 'Spam'), ('UNDER_REVIEW', 'Under Review'), ('RESPONDED', 'Responded'), ('REOPENED', 'Reopened'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], max_length=20, null=True),
        ),
    ]
