# Generated by Django 4.2.30 on 2026-07-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0002_fix_status_history_previous_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='secret_code',
            field=models.CharField(blank=True, help_text='Hashed secret code issued to anonymous submitters for tracking (plain-text shown once at creation).', max_length=128, null=True),
        ),
    ]
