# Generated by Django 4.2.30 on 2026-07-25 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('grievances', '0003_fix_secret_code_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='department',
            field=models.ForeignKey(blank=True, help_text='The department responsible for handling this grievance.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grievances', to='accounts.department'),
        ),
    ]
