# Generated by Django 4.2.30 on 2026-07-26 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grievances', '0004_alter_grievance_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='escalated_to',
            field=models.ForeignKey(blank=True, help_text='The officer this grievance was escalated to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_grievances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grievance',
            name='escalation_level',
            field=models.PositiveSmallIntegerField(default=0, help_text='Current escalation level (0 = normal, 1+, 2+, etc.).'),
        ),
    ]
