# Generated by Django 4.2.30 on 2026-07-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0005_grievance_escalated_to_grievance_escalation_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='current_status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('SPAM', 'Spam'), ('UNDER_REVIEW', 'Under Review'), ('RESPONDED', 'Responded'), ('REOPENED', 'Reopened'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], db_index=True, default='SUBMITTED', max_length=20),
        ),
    ]
