# Generated by Django 4.2.30 on 2026-07-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0005_grievance_escalated_to_grievance_escalation_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='current_status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('SPAM', 'Spam'), ('UNDER_REVIEW', 'Under Review'), ('RESPONDED', 'Responded'), ('REOPENED', 'Reopened'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], default='SUBMITTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='new_status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('SPAM', 'Spam'), ('UNDER_REVIEW', 'Under Review'), ('RESPONDED', 'Responded'), ('REOPENED', 'Reopened'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('SUBMITTED', 'Submitted'), ('SPAM', 'Spam'), ('UNDER_REVIEW', 'Under Review'), ('RESPONDED', 'Responded'), ('REOPENED', 'Reopened'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], max_length=20, null=True),
        ),
    ]
