# Generated by Django 4.2.30 on 2026-07-31 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grievances', '0006_alter_grievance_current_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('REOPEN', 'Reopen Request'), ('REJECTION_APPEAL', 'Rejection Appeal'), ('SPAM_APPEAL', 'Spam Appeal'), ('ESCALATION', 'Escalation')], help_text='Type of request (REOPEN, REJECTION_APPEAL, SPAM_APPEAL, ESCALATION).', max_length=30)),
                ('reason', models.TextField(help_text='Mandatory justification provided by student or system.')),
                ('attachment', models.FileField(blank=True, help_text='Optional supporting document attached to request.', null=True, upload_to='request_attachments/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FORWARDED', 'Forwarded'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Current review status of the request.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_remark', models.TextField(blank=True, default='', help_text='Remarks/notes added by Campus Admin during review.')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Timestamp when admin resolved (forwarded or rejected) the request.', null=True)),
                ('forwarded_department', models.ForeignKey(blank=True, help_text='Department this request was forwarded to by the admin.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarded_requests', to='accounts.department')),
                ('grievance', models.ForeignKey(help_text='The grievance associated with this request.', on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='grievances.grievance')),
                ('reviewed_by_admin', models.ForeignKey(blank=True, help_text='Campus Admin who reviewed this request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, help_text='The student/user submitting the request (null for automated escalations).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
