# Generated by Django 4.2.30 on 2026-07-31 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0007_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='original_status',
            field=models.CharField(blank=True, choices=[('SUBMITTED', 'Submitted'), ('SPAM', 'Spam'), ('UNDER_REVIEW', 'Under Review'), ('RESPONDED', 'Responded'), ('REOPENED', 'Reopened'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected'), ('APPEAL_PENDING', 'Appeal Pending'), ('CLOSED', 'Closed')], help_text='Grievance status before the request was submitted — restored if the request is rejected.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='current_status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('SPAM', 'Spam'), ('UNDER_REVIEW', 'Under Review'), ('RESPONDED', 'Responded'), ('REOPENED', 'Reopened'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected'), ('APPEAL_PENDING', 'Appeal Pending'), ('CLOSED', 'Closed')], default='SUBMITTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='new_status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('SPAM', 'Spam'), ('UNDER_REVIEW', 'Under Review'), ('RESPONDED', 'Responded'), ('REOPENED', 'Reopened'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected'), ('APPEAL_PENDING', 'Appeal Pending'), ('CLOSED', 'Closed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('SUBMITTED', 'Submitted'), ('SPAM', 'Spam'), ('UNDER_REVIEW', 'Under Review'), ('RESPONDED', 'Responded'), ('REOPENED', 'Reopened'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected'), ('APPEAL_PENDING', 'Appeal Pending'), ('CLOSED', 'Closed')], max_length=20, null=True),
        ),
    ]
