# Generated by Django 4.2.30 on 2026-07-31 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0008_request_original_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('FORWARDED', 'Forwarded'), ('REJECTED', 'Rejected'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='PENDING', help_text='Current review status of the request.', max_length=20),
        ),
    ]
