# Generated by Django 4.2.30 on 2026-08-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0009_alter_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='is_sensitive',
            field=models.BooleanField(default=False, help_text='Flags that the grievance contains sensitive content that department staff/HOD/Campus Admin must confirm before viewing.'),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='current_status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('IN_PROGRESS', 'In Progress'), ('REOPENED', 'Reopened'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], default='SUBMITTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='request',
            name='original_status',
            field=models.CharField(blank=True, choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('IN_PROGRESS', 'In Progress'), ('REOPENED', 'Reopened'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], help_text='Grievance status before the request was submitted — restored if the request is rejected.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='new_status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('IN_PROGRESS', 'In Progress'), ('REOPENED', 'Reopened'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('IN_PROGRESS', 'In Progress'), ('REOPENED', 'Reopened'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], max_length=20, null=True),
        ),
    ]
