# Generated by Django 4.2.30 on 2026-08-07 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0010_grievance_is_sensitive_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReopenAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='reopen_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('grievance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reopen_attachments', to='grievances.grievance')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
