# Generated by Django 4.2.30 on 2026-08-07 17:00

from django.db import migrations


def fix_appeal_pending(apps, schema_editor):
    Grievance = apps.get_model('grievances', 'Grievance')
    Request = apps.get_model('grievances', 'Request')

    for grievance in Grievance.objects.filter(current_status='APPEAL_PENDING'):
        # Find the pending request for this grievance to get original_status
        req = Request.objects.filter(
            grievance=grievance,
            request_type__in=['REJECTION_APPEAL', 'SPAM_APPEAL'],
            status='PENDING'
        ).first()
        if req and req.original_status:
            grievance.current_status = req.original_status
        else:
            # Fallback: REJECTED is the most common original status
            grievance.current_status = 'REJECTED'
        grievance.save(update_fields=['current_status'])


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0011_reopenattachment'),
    ]

    operations = [
        migrations.RunPython(fix_appeal_pending, migrations.RunPython.noop),
    ]