# Generated by Django 4.2.30 on 2026-08-09 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grievances', '0012_fix_appeal_pending_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='The reminder comment asking for a status update.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grievance', models.OneToOneField(help_text='The grievance this reminder comment belongs to (max one per grievance).', on_delete=django.db.models.deletion.CASCADE, related_name='status_comment', to='grievances.grievance')),
                ('user', models.ForeignKey(help_text='The submitter who posted the reminder comment.', on_delete=django.db.models.deletion.CASCADE, related_name='status_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
