# Generated by Django 4.2.30 on 2026-08-17 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grievances', '0014_statuscomment_per_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='spam_reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When the department officer made the final spam decision.', null=True),
        ),
        migrations.AddField(
            model_name='grievance',
            name='spam_reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Department officer who made the final spam decision.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spam_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grievance',
            name='spam_status',
            field=models.CharField(blank=True, choices=[('REVIEW', 'Needs Review'), ('SPAM', 'Confirmed Spam'), ('NOT_SPAM', 'Not Spam')], default=None, help_text='Department-side spam classification (null = never flagged by AI). REVIEW = AI flagged, awaiting department decision; SPAM = confirmed spam (kept out of the normal workflow); NOT_SPAM = accepted as genuine.', max_length=20, null=True),
        ),
    ]
