import { Link } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import logo from '../assets/logo.png';

const roleHome = {
  STUDENT: { eyebrow: 'Student workspace', title: 'Your concerns deserve a clear path forward.', description: 'Create grievances, follow department responses, and keep every update in one place.', dashboard: '/dashboard/student', dashboardLabel: 'Open my dashboard', primary: 'Submit a grievance', primaryTo: '/grievances/new', accent: 'student' },
  STAFF: { eyebrow: 'Staff workspace', title: 'A simple, private way to raise campus issues.', description: 'Submit and follow your grievances from one personal dashboard, with clear status updates along the way.', dashboard: '/dashboard/student', dashboardLabel: 'Open my dashboard', primary: 'Submit a grievance', primaryTo: '/grievances/new', accent: 'student' },
  HOD: { eyebrow: 'Department workspace', title: 'Keep your department’s resolutions moving.', description: 'Review grievances assigned to your department and see which concerns need attention first.', dashboard: '/dashboard/department', dashboardLabel: 'Open department dashboard', primary: 'Review department grievances', primaryTo: '/dashboard/department', accent: 'department' },
  CAMPUS_ADMIN: { eyebrow: 'Campus administration', title: 'See the whole grievance system at a glance.', description: 'Monitor campus-wide activity, escalations, resolution progress, and spam flags from one overview.', dashboard: '/dashboard/admin', dashboardLabel: 'Open system overview', primary: 'View system dashboard', primaryTo: '/dashboard/admin', accent: 'admin' },
};

const Landing = () => {
  const { user } = useAuth();
  const userRole = (user?.role || '').toUpperCase();
  const workspace = roleHome[userRole] || roleHome.STUDENT;
  const displayName = user?.first_name || user?.username || user?.email?.split('@')[0] || 'there';

  if (user) {
    return <div className={`role-home role-home-${workspace.accent}`}>
      <section className="role-home-hero"><div className="role-home-container"><div className="role-home-copy"><div className="hero-badge"><span className="badge-pulse" />{workspace.eyebrow}</div><p className="role-greeting">Welcome back, {displayName}</p><h1>{workspace.title}</h1><p>{workspace.description}</p><div className="hero-cta-group"><Link to={workspace.primaryTo} className="btn btn-hero-primary">{workspace.primary}<span className="btn-arrow">→</span></Link><Link to={workspace.dashboard} className="btn btn-hero-secondary">{workspace.dashboardLabel}</Link></div></div><aside className="role-home-panel"><img src={logo} alt="IOE Pulchowk Campus Logo" /><span>Your workspace</span><strong>{workspace.eyebrow}</strong><p>Secure access based on your campus role.</p><div className="role-home-panel-line" /><small>IOE Pulchowk Campus · Grievance Portal</small></aside></div></section>
      <section className="role-home-steps"><div><span>01</span><h2>{userRole === 'HOD' ? 'Review assigned issues' : userRole === 'CAMPUS_ADMIN' ? 'Monitor campus activity' : 'Share your concern'}</h2><p>{userRole === 'HOD' ? 'See department grievances in one focused queue.' : userRole === 'CAMPUS_ADMIN' ? 'View system-wide volume and priority signals.' : 'Submit a clear description with optional evidence.'}</p></div><div><span>02</span><h2>{userRole === 'HOD' ? 'Follow progress' : userRole === 'CAMPUS_ADMIN' ? 'Identify what needs action' : 'Track each update'}</h2><p>{userRole === 'HOD' ? 'Use filters and status to stay organised.' : userRole === 'CAMPUS_ADMIN' ? 'Keep an eye on escalations and spam flags.' : 'See department responses and your status history.'}</p></div><div><span>03</span><h2>{userRole === 'HOD' ? 'Resolve with clarity' : userRole === 'CAMPUS_ADMIN' ? 'Support resolution' : 'Stay informed'}</h2><p>{userRole === 'HOD' ? 'Keep the resolution journey transparent.' : userRole === 'CAMPUS_ADMIN' ? 'Use the overview to keep the workflow healthy.' : 'Your dashboard keeps the full record together.'}</p></div></section>
    </div>;
  }

  return <div className="landing-page"><section className="hero-section"><div className="hero-container"><div className="hero-badge"><span className="badge-pulse" />Institute of Engineering · Pulchowk Campus</div><div className="hero-content"><div className="hero-logo-wrapper"><img src={logo} alt="IOE Pulchowk Campus Logo" className="hero-logo" /></div><h1 className="hero-title">IOE Pulchowk <span className="gradient-text">Grievance Portal</span></h1><p className="hero-description">A clear and accountable way for the Pulchowk community to raise campus concerns, receive responses, and follow progress.</p><div className="hero-cta-group"><Link to="/register" className="btn btn-hero-primary">Create an account <span className="btn-arrow">→</span></Link><Link to="/grievances/track" className="btn btn-hero-secondary">Track a grievance</Link><Link to="/login" className="btn btn-hero-outline">Account login</Link></div></div></div></section><section className="stats-banner"><div className="stats-container"><div className="stat-card"><div className="stat-value">Clear</div><div className="stat-label">Status updates</div></div><div className="stat-card"><div className="stat-value">Private</div><div className="stat-label">Anonymous option</div></div><div className="stat-card"><div className="stat-value">8+</div><div className="stat-label">Campus departments</div></div><div className="stat-card"><div className="stat-value">One place</div><div className="stat-label">For every update</div></div></div></section><section className="features-section"><div className="section-header"><h2>A better path to resolution</h2><p>Designed to connect students, staff, departments, and campus administration.</p></div><div className="features-grid"><div className="feature-card"><div className="feature-icon">↗</div><h3>Route with confidence</h3><p>Send a concern to the responsible department from the start.</p></div><div className="feature-card"><div className="feature-icon">◌</div><h3>Stay in the loop</h3><p>Follow responses and every status change from your account.</p></div><div className="feature-card"><div className="feature-icon">⌁</div><h3>Built for accountability</h3><p>Clear histories make each resolution journey easy to understand.</p></div></div></section></div>;
};

export default Landing;
